version: '3.0'
services:
  db:
    image: postgres
    restart: always
    hostname: db
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bancodigital
